#!/usr/bin/env python3
"""Sync Cursor feature manifest, tier-filtered help, and compliance rule activation."""
from __future__ import annotations

import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

FOSS_ENABLED = [
    "rules",
    "commands",
    "hooks",
    "skills",
    "subagents",
    "modes",
    "worktrees",
    "permissions",
    "parallel_scope",
    "build_automation",
    "feature_radar",
    "plugin_pack",
    "cli_example",
    "mcp_foss_example",
]

COMMERCIAL_ONLY = [
    "cloud_agents",
    "bugbot",
    "automations",
    "approval_agents",
    "mcp_commercial_example",
    "android_commercial_patterns",
]

COMMERCIAL_COPY = {
    ".cursor/BUGBOT.md.commercial.example": ".cursor/BUGBOT.md",
    ".cursor/environment.json.commercial.example": ".cursor/environment.json",
}

FOSS_DISTRIBUTION = (
    "Pure FOSS under MIT license distributed via GitHub Releases and "
    "platform-appropriate channels (F-Droid, Winget, GitHub Pages, or package indexes)."
)

COMMERCIAL_DISTRIBUTION = (
    "Commercial distribution — proprietary SDKs allowed where documented; "
    "App Store, SaaS, or enterprise channels. See docs/CURSOR_COMMERCIAL_ACTIVATION.md."
)


def read_json(path: Path) -> dict:
    if not path.is_file():
        return {}
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, data: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")


def set_rule_always_apply(path: Path, enabled: bool) -> None:
    if not path.is_file():
        return
    text = path.read_text(encoding="utf-8")
    if "alwaysApply:" not in text:
        return
    replacement = f"alwaysApply: {'true' if enabled else 'false'}"
    text = re.sub(r"alwaysApply:\s*(true|false)", replacement, text, count=1)
    path.write_text(text, encoding="utf-8")


def patch_initialization_distribution(root: Path, tier: str) -> None:
    path = root / "docs/INITIALIZATION_PROMPT.md"
    if not path.is_file():
        return
    text = path.read_text(encoding="utf-8")
    block = FOSS_DISTRIBUTION if tier == "foss" else COMMERCIAL_DISTRIBUTION
    text = re.sub(
        r"\*\*Distribution:\*\*[^\n]+",
        f"**Distribution:** {block}",
        text,
        count=1,
    )
    text = text.replace(
        "- **`.cursorrules` / `AGENTS.md`:**",
        "- **`AGENTS.md` / `.cursor/rules/`:**",
    )
    path.write_text(text, encoding="utf-8")


def generate_help(root: Path, tier: str) -> None:
    foss_rows = [
        ("Rules (`.mdc`)", "`.cursor/rules/`", "both"),
        ("Slash commands (26)", "`.cursor/commands/`", "both"),
        ("Hooks", "`.cursor/hooks.json`", "both"),
        ("Skills (7)", "`.cursor/skills/`", "both"),
        ("Subagents (3)", "`.cursor/agents/`", "both"),
        ("Worktrees", "`.cursor/worktrees.json`", "both"),
        ("Auto-review permissions", "`.cursor/permissions.json`", "both"),
        ("Sandbox (optional)", "`.cursor/sandbox.json.example`", "both"),
        ("Plugin pack", "`.cursor-plugin/plugin.json` + `scripts/pack-cursor-plugin.*`", "both"),
        ("CLI (opt-in)", "`.github/workflow-examples/cursor-agent.yml`", "both"),
        ("GitHub MCP (optional)", "`.cursor/mcp.foss.example`", "foss"),
        ("Feature radar", "`scripts/cursor-feature-radar.sh`", "both"),
    ]
    commercial_rows = [
        ("Cloud Agents", "`.cursor/environment.json.commercial.example`", "commercial"),
        ("Bugbot", "`.cursor/BUGBOT.md.commercial.example`", "commercial"),
        ("Cloud conversation hooks", "`.cursor/hooks.cloud.commercial.example.json`", "commercial"),
        ("Automations recipes", "`docs/CURSOR_AUTOMATIONS.commercial.md`", "commercial"),
        ("Commercial MCP", "`.cursor/mcp.commercial.example`", "commercial"),
        ("Android commercial patterns", "`modules/android/COMMERCIAL.md`", "commercial"),
    ]
    lines = [
        "# Cursor features (human cheat sheet)",
        "",
        f"> Generated by `scripts/sync-cursor-features.py` — tier: **{tier}**",
        "",
        "## Active features",
        "",
        "| Feature | Path | Tier |",
        "|---------|------|------|",
    ]
    for name, path, row_tier in foss_rows:
        lines.append(f"| {name} | {path} | {row_tier} |")
    if tier == "commercial":
        lines.extend(["", "## Commercial tier (activation required)", ""])
        lines.extend(["| Feature | Example | Tier |", "|---------|---------|------|"])
        for row in commercial_rows:
            lines.append(f"| {row[0]} | {row[1]} | {row[2]} |")
        lines.extend(
            [
                "",
                "See [CURSOR_COMMERCIAL_ACTIVATION.md](../CURSOR_COMMERCIAL_ACTIVATION.md).",
            ]
        )
    else:
        lines.extend(
            [
                "",
                "Commercial-only features stay as `*.commercial.example` — see "
                "[CURSOR_INTEGRATIONS.md](../CURSOR_INTEGRATIONS.md).",
            ]
        )
    lines.extend(["", "Full matrix: [CURSOR_INTEGRATIONS.md](../CURSOR_INTEGRATIONS.md).", ""])
    (root / "docs/help/CURSOR_FEATURES.md").write_text("\n".join(lines), encoding="utf-8")


def sync(root: Path, tier: str, copy_commercial: bool, patch_init: bool = False) -> None:
    if tier not in ("foss", "commercial"):
        raise ValueError(f"invalid tier: {tier}")

    cursor_dir = root / ".cursor"
    cursor_dir.mkdir(exist_ok=True)

    enabled = list(FOSS_ENABLED)
    hidden = list(COMMERCIAL_ONLY)
    if tier == "commercial":
        enabled.extend(COMMERCIAL_ONLY)
        hidden = []

    stack_sel = read_json(cursor_dir / "stack-selection.json")
    stack_sel["distribution_tier"] = tier
    stack_sel.setdefault("stack", stack_sel.get("stack", "multi"))
    stack_sel["cursor_features_enabled"] = enabled
    stack_sel["cursor_features_hidden"] = hidden
    stack_sel["cursor_features_synced_at"] = (
        datetime.now(timezone.utc).replace(microsecond=0).isoformat()
    )
    write_json(cursor_dir / "stack-selection.json", stack_sel)

    manifest = {
        "distribution_tier": tier,
        "enabled": enabled,
        "hidden": hidden,
        "generated_at": stack_sel["cursor_features_synced_at"],
    }
    write_json(cursor_dir / "cursor-features.json", manifest)

    foss_rule = root / ".cursor/rules/foss-compliance.mdc"
    commercial_rule = root / ".cursor/rules/commercial-compliance.mdc"
    set_rule_always_apply(foss_rule, tier == "foss")
    set_rule_always_apply(commercial_rule, tier == "commercial")

    if tier == "commercial" and copy_commercial:
        for src, dst in COMMERCIAL_COPY.items():
            src_path = root / src
            dst_path = root / dst
            if src_path.is_file() and not dst_path.exists():
                dst_path.write_text(src_path.read_text(encoding="utf-8"), encoding="utf-8")

    generate_help(root, tier)
    if patch_init:
        patch_initialization_distribution(root, tier)


def main() -> int:
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument("--root", default=".")
    parser.add_argument("--tier", default="foss", choices=("foss", "commercial"))
    parser.add_argument("--copy-commercial", action="store_true")
    parser.add_argument("--patch-init", action="store_true", help="Rewrite INITIALIZATION_PROMPT Distribution section")
    args = parser.parse_args()
    root = Path(args.root).resolve()
    sync(root, args.tier, args.copy_commercial, patch_init=args.patch_init)
    print(f"Synced Cursor features (tier={args.tier})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
